### ISSUE TITLE
logrotate module unable to add scripts

### ISSUE THREAD

**Issue by davidcusatis** [blueboxgroup/ursula#1335]
https://github.com/blueboxgroup/ursula/blob/master/library/logrotate.py

there is currently no way to add a script for postrotate and prerotate. the module only supports options. a use case would be something like the following:

```
- name: set up log rotation for horizon
  logrotate: name=apache2 path=/var/log/apache2/*.log
  args:
    options:
        - daily
        - missingok
        - rotate 7
        - compress
        - delaycompress
        - notifempty
        - create 640 root adm
        - sharedscripts
    scripts:
        postrotate: "if /etc/init.d/apache2 status > /dev/null ; then \
                    /etc/init.d/apache2 reload > /dev/null; \
                fi;"
        prerotate: "if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
            run-parts /etc/logrotate.d/httpd-prerotate; \
        fi; \ "
```
