### ISSUE TITLE
It's not consistent to add repo for ubuntu and centos/redhat

### ISSUE THREAD

**Issue by chengtcli** [blueboxgroup/ursula#2331]
The `repos` role is able to add repository for ubuntu and centos/redhat.
But the usages are different(For ubuntu, we need to specify the repo_url and key_url. For redhat, we just specify the repo name which is defined in repos/default/main.yml or all.yml):
```
  - role: repos
    repos:
      - repo: 'deb {{ apt_repos.ceph.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ceph.key_url }}'
    when: os == 'ubuntu'

  - role: repos
    repo: ceph
    when: os = 'rhel'
```

I am wondering if we can make some improvements of the `repos` role, so that we can add repository without considering what the OS it is. It may be like following example.
```
  - role: repos
    repos:
      - ceph
```
